#!/usr/bin/env python3
#-*- coding: utf-8 -*-

import sys
import os
import inspect
import traceback
import subprocess
import re
import contextlib
from io import StringIO


#############################################
# temporarily replacing sys.stdout and sys.stderr
@contextlib.contextmanager
def capture_sys_output():
    capture_out, capture_err = StringIO(), StringIO()
    current_out, current_err = sys.stdout, sys.stderr
    try:
        sys.stdout, sys.stderr = capture_out, capture_err
        yield sys.stdout, sys.stderr
    finally:
        sys.stdout, sys.stderr = current_out, current_err


def unittest_result_summary(x):
    print( "%s" % x )
    test_result_summary = ""
    searchObj = re.search(r'(Ran \d+ tests)', x, re.M)
    if searchObj:
        test_result_summary += searchObj.group()
        searchObj = re.search(r'(FAILED \(failures=\d+\))', x, re.M)
        if searchObj:
             test_result_summary += ' '+searchObj.group()
        #print ( 'Summary: '+test_result_summary+'\n' )
    return test_result_summary

def launch_test(py_exec_path):
    if not os.path.exists(py_exec_path):
        print ('WARNING: '+py_exec_path+' not exist. '
               'Development environment is not good enough!')
        return ""
    print ('\n################# Launch test with: '
           +py_exec_path+' #################\n')

    cmd_folder = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile(inspect.currentframe() ))[0]))
    p = subprocess.Popen([py_exec_path, cmd_folder+"/test_virt_dup.py"],
                         universal_newlines=True,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    out, err = p.communicate()
    return unittest_result_summary(out+err)


def main():

    PY_PATH="/usr/bin/python3"
    p3_test_result_summary = launch_test(PY_PATH)


if __name__ == '__main__':
    main()



